[package]
name = "ere-sp1"
version = "0.1.0"
edition = "2021"

[dependencies]
ere-platform-sp1 = { git = "https://github.com/eth-applied-research-group/ere", rev = "2ede04de0d5993aa505624ab18dfcb810637c2d6", default-features = false }
